import { InterviewRole } from '../types';

export const ROLE_QUESTIONS: Record<InterviewRole, string[]> = {
  software_engineer: [
    "Welcome! Let's begin with your background. Can you walk me through your most recent project and the technical challenges you faced?",
    "Tell me about your experience with data structures and algorithms. Can you describe a time when you optimized a piece of code?",
    "How do you approach system design? Let's say you need to design a scalable system - how would you approach this?",
    "Describe your experience with version control and collaborative development. How do you handle merge conflicts?",
    "Let's discuss code quality. What practices do you follow to ensure maintainable and testable code?",
    "How do you stay updated with new technologies? Can you give an example of something new you learned recently?",
    "Tell me about a challenging bug you debugged. What was your process?",
    "We've covered a lot of ground. Do you have any questions about the role or the team?",
  ],

  data_analyst: [
    "Hello! Let's start with your analytical background. What types of datasets have you worked with?",
    "Can you walk me through your data cleaning and preprocessing workflow?",
    "What's your experience with SQL? Can you describe a complex query you've written?",
    "Tell me about a time when you discovered an important insight from data analysis. What was the business impact?",
    "How do you approach data visualization? What tools do you prefer and why?",
    "Describe your experience with statistical analysis. How do you determine which methods to use?",
    "How do you communicate technical findings to non-technical stakeholders?",
    "What questions do you have about the data analysis work we do here?",
  ],

  data_scientist: [
    "Great to meet you! Tell me about your machine learning experience. What models have you built?",
    "Can you explain the difference between supervised and unsupervised learning with examples from your work?",
    "How do you handle imbalanced datasets? What techniques have you used?",
    "Walk me through your feature engineering process. How do you decide which features to create?",
    "How do you evaluate model performance? Can you explain precision, recall, and F1-score?",
    "Tell me about a model you deployed to production. What challenges did you face?",
    "How do you approach A/B testing? Can you share an example?",
    "Before we conclude, do you have any questions about our data science team?",
  ],

  web_developer: [
    "Welcome! Let's discuss your web development experience. What's your favorite tech stack and why?",
    "Can you explain your approach to responsive design? How do you ensure cross-browser compatibility?",
    "Tell me about a complex frontend feature you've implemented. What were the challenges?",
    "How do you handle state management in your applications?",
    "Describe your backend development experience. What APIs have you built?",
    "How do you approach web security? What practices do you follow?",
    "Tell me about your testing strategy for web applications.",
    "Any questions about our development process or tech stack?",
  ],

  ui_ux_designer: [
    "Welcome! Can you walk me through your design process from research to final deliverables?",
    "Tell me about a project where you conducted user research. What methods did you use and what did you learn?",
    "How do you approach creating user personas? Can you give an example?",
    "Describe your experience with prototyping tools. How do you test your designs?",
    "How do you handle design feedback and criticism? Can you share an example?",
    "Walk me through a design challenge where you had to balance user needs with business requirements.",
    "How do you ensure accessibility in your designs?",
    "Before we wrap up, do you have any questions about the design team?",
  ],

  product_manager: [
    "Hello! Tell me about your experience in product management. What products have you managed?",
    "How do you prioritize features in your product roadmap? What framework do you use?",
    "Describe a time when you had to make a difficult product decision with limited data.",
    "How do you gather and incorporate customer feedback into your product?",
    "Walk me through how you define success metrics for a new feature.",
    "Tell me about your experience working with engineering and design teams.",
    "How do you handle stakeholder conflicts regarding product direction?",
    "What questions do you have about our product strategy?",
  ],

  digital_marketing: [
    "Welcome! Let's discuss your digital marketing experience. What campaigns have you worked on?",
    "How do you approach SEO strategy? What tactics have you found most effective?",
    "Tell me about a successful paid advertising campaign you managed. What made it successful?",
    "How do you measure ROI for your marketing campaigns?",
    "Describe your experience with social media marketing. What platforms do you specialize in?",
    "How do you approach content marketing strategy?",
    "Tell me about a campaign that didn't meet expectations. What did you learn?",
    "Do you have any questions about our marketing initiatives?",
  ],

  hr: [
    "Hello! Tell me about your experience in human resources. What areas have you worked in?",
    "How do you approach the recruitment process? What methods do you use to find top talent?",
    "Describe a challenging employee relations situation you've handled.",
    "How do you stay updated on employment laws and regulations?",
    "Tell me about your experience with performance management systems.",
    "How do you approach employee engagement and retention initiatives?",
    "Describe a training or development program you've implemented.",
    "Before we conclude, do you have any questions about our HR team?",
  ],

  finance: [
    "Welcome! Tell me about your background in finance. What areas have you specialized in?",
    "Walk me through your financial modeling experience. What types of models have you built?",
    "How do you approach financial analysis and reporting?",
    "Tell me about a time when your financial analysis influenced a major business decision.",
    "Describe your experience with budgeting and forecasting.",
    "How do you ensure accuracy in your financial work?",
    "Tell me about a challenging audit or compliance situation you've handled.",
    "What questions do you have about our finance operations?",
  ],

  sales: [
    "Hello! Let's discuss your sales experience. What industries have you worked in?",
    "Walk me through your sales process from prospecting to closing.",
    "Tell me about your most successful sale. What made it successful?",
    "How do you handle objections from potential clients?",
    "Describe your experience with CRM systems. How do you manage your pipeline?",
    "Tell me about a time when you lost a sale. What did you learn?",
    "How do you build and maintain client relationships?",
    "Do you have any questions about our sales team and targets?",
  ],

  customer_support: [
    "Welcome! Tell me about your customer service experience.",
    "How do you handle difficult or upset customers? Can you give an example?",
    "Describe a time when you went above and beyond for a customer.",
    "How do you prioritize multiple customer issues at once?",
    "Tell me about your experience with support tools and ticketing systems.",
    "How do you handle situations where you don't know the answer to a customer's question?",
    "Describe your approach to maintaining a positive attitude during challenging interactions.",
    "Before we conclude, do you have any questions about our support team?",
  ],

  teacher: [
    "Hello! Tell me about your teaching experience. What subjects and grade levels have you taught?",
    "How do you approach lesson planning? Can you walk me through your process?",
    "Describe your classroom management style. How do you handle disruptive behavior?",
    "How do you differentiate instruction for students with different learning needs?",
    "Tell me about your experience with assessment and grading.",
    "How do you incorporate technology into your teaching?",
    "Describe how you communicate with parents about student progress.",
    "Do you have any questions about our school or teaching position?",
  ],

  doctor: [
    "Welcome, Doctor. Tell me about your medical training and specialization.",
    "How do you approach diagnosis when presented with conflicting symptoms?",
    "Describe a challenging case you've handled. What was your approach?",
    "How do you communicate difficult news to patients and their families?",
    "Tell me about your experience working in a multidisciplinary team.",
    "How do you stay current with medical research and developments?",
    "Describe your approach to patient education and preventive care.",
    "Before we conclude, do you have any questions about our healthcare facility?",
  ],

  nurse: [
    "Hello! Tell me about your nursing experience. What departments have you worked in?",
    "How do you prioritize patient care when managing multiple patients?",
    "Describe a challenging patient situation you've handled.",
    "How do you handle stressful situations in a clinical environment?",
    "Tell me about your experience with patient education.",
    "How do you ensure effective communication with doctors and other healthcare professionals?",
    "Describe your approach to maintaining patient dignity and comfort.",
    "Do you have any questions about our nursing team?",
  ],

  lawyer: [
    "Welcome! Tell me about your legal experience. What areas of law have you practiced?",
    "How do you approach case preparation? Walk me through your process.",
    "Describe a challenging case you worked on. What was the outcome?",
    "How do you manage client expectations while maintaining ethical standards?",
    "Tell me about your experience in legal research and writing.",
    "How do you handle negotiations with opposing counsel?",
    "Describe your approach to maintaining work-life balance in a demanding profession.",
    "Before we conclude, do you have any questions about our firm?",
  ],

  business_analyst: [
    "Hello! Tell me about your experience as a business analyst.",
    "How do you approach requirements gathering? What techniques do you use?",
    "Walk me through a process improvement project you've led.",
    "How do you translate technical requirements for non-technical stakeholders?",
    "Describe your experience with data analysis and reporting tools.",
    "Tell me about a time when you identified a significant business opportunity through your analysis.",
    "How do you handle conflicting requirements from different stakeholders?",
    "Do you have any questions about our business analysis team?",
  ],

  content_creator: [
    "Welcome! Tell me about your content creation experience. What platforms do you work with?",
    "How do you approach content strategy and planning?",
    "Walk me through your creative process from idea to published content.",
    "How do you measure content performance? What metrics do you track?",
    "Tell me about a piece of content that performed exceptionally well. What made it successful?",
    "How do you stay authentic while also meeting brand or audience expectations?",
    "Describe how you handle negative feedback or criticism of your content.",
    "Do you have any questions about our content strategy?",
  ],

  journalist: [
    "Hello! Tell me about your journalism experience. What beats have you covered?",
    "How do you approach researching and verifying information before publishing?",
    "Describe a challenging story you covered. How did you navigate sensitive issues?",
    "How do you build and maintain relationships with sources?",
    "Tell me about your experience with different media formats - print, digital, broadcast.",
    "How do you maintain objectivity while covering controversial topics?",
    "Describe your approach to interviewing difficult or reluctant subjects.",
    "Before we conclude, do you have any questions about our publication?",
  ],

  civil_services: [
    "Welcome! Tell me about your interest in civil services. What motivates you?",
    "How do you approach policy analysis and implementation?",
    "Describe a situation where you had to balance competing public interests.",
    "How would you handle a situation where political pressure conflicts with ethical standards?",
    "Tell me about your understanding of governance and public administration.",
    "How do you approach crisis management in a public service context?",
    "Describe your vision for improving public service delivery.",
    "Do you have any questions about our civil service expectations?",
  ],

  mechanical_engineer: [
    "Hello! Tell me about your mechanical engineering experience. What industries have you worked in?",
    "Walk me through a design project you've worked on. What was your role?",
    "How do you approach thermal and fluid analysis in your projects?",
    "Describe your experience with CAD software and simulation tools.",
    "Tell me about a design challenge you overcame. What was your solution?",
    "How do you ensure quality and safety in your engineering work?",
    "Describe your experience with manufacturing processes and materials selection.",
    "Before we conclude, do you have any questions about our engineering team?",
  ],

  electrical_engineer: [
    "Welcome! Tell me about your electrical engineering background. What areas have you specialized in?",
    "Walk me through a circuit design project you've worked on.",
    "How do you approach power system analysis and design?",
    "Describe your experience with electronics, embedded systems, or control systems.",
    "Tell me about a challenging electrical problem you solved.",
    "How do you ensure safety and compliance with electrical codes?",
    "Describe your experience with testing and troubleshooting electrical systems.",
    "Do you have any questions about our electrical engineering projects?",
  ],

  hotel_management: [
    "Hello! Tell me about your experience in hospitality management.",
    "How do you approach guest satisfaction and service quality?",
    "Describe a challenging guest situation you've handled.",
    "How do you manage and motivate front-line staff?",
    "Tell me about your experience with revenue management and pricing strategies.",
    "How do you handle operational challenges during peak seasons?",
    "Describe your approach to staff training and development.",
    "Before we conclude, do you have any questions about our property?",
  ],

  banking: [
    "Welcome! Tell me about your experience in the banking sector.",
    "How do you approach risk assessment in lending decisions?",
    "Describe your understanding of banking regulations and compliance.",
    "Tell me about your experience with financial products and services.",
    "How do you build and maintain relationships with banking customers?",
    "Describe a time when you identified and prevented a potential fraud.",
    "How do you stay updated on financial market trends and regulations?",
    "Do you have any questions about our banking operations?",
  ],

  general: [
    "Hello! Let's start with you telling me about yourself. What brings you to this opportunity?",
    "What are your greatest professional strengths? Can you give specific examples?",
    "Tell me about a challenging situation at work and how you handled it.",
    "Where do you see yourself in five years? What are your career aspirations?",
    "Describe a time when you had to work with a difficult colleague or client.",
    "How do you handle pressure and tight deadlines?",
    "Tell me about a mistake you made and what you learned from it.",
    "Why are you interested in this role? What do you know about our organization?",
    "What questions do you have for me about the role or our organization?",
  ],
};

export const FOLLOW_UPS = [
  "That's interesting! Can you elaborate on that point?",
  "Great answer! Can you give me a specific example of when you applied that?",
  "How would you handle a situation where that approach didn't work?",
  "What were the results of that decision? How did you measure success?",
  "That's good context. What specific tools or methodologies did you use?",
  "Were there any trade-offs in that approach? What alternatives did you consider?",
  "How did you collaborate with others on this? What was your role in the team?",
  "What did you learn from that experience? Would you do anything differently?",
  "How did that experience shape your professional approach?",
  "Can you quantify the impact of that work?",
];
